/* Сквозная проверка в браузере: старые функции DDX Vision не сломаны, новые AI-экраны работают.
   Запуск: node tests/e2e.mjs  (нужен playwright; сервер поднимается сам) */
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
let chromium; try { ({ chromium } = await import('playwright')); } catch (e) { ({ chromium } = await import('/opt/node-tools/node_modules/playwright/index.mjs')); }

const MIME = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.png': 'image/png', '.webmanifest': 'application/manifest+json' };
const srv = http.createServer((req, res) => { const u = decodeURIComponent(req.url.split('?')[0]); const f = path.join(root, u === '/' ? 'index.html' : u); if (!f.startsWith(root) || !fs.existsSync(f)) { res.writeHead(404); res.end(); return; } res.writeHead(200, { 'content-type': MIME[path.extname(f)] || 'application/octet-stream' }); res.end(fs.readFileSync(f)); });
await new Promise(r => srv.listen(0, '127.0.0.1', r)); const BASE = 'http://127.0.0.1:' + srv.address().port + '/index.html';

// мок боевого сервиса DDX (контракт описан в docs/AI-ENGINE.md)
const mock = http.createServer((req, res) => {
  const cors = { 'access-control-allow-origin': '*', 'access-control-allow-headers': 'authorization,content-type', 'content-type': 'application/json' };
  if (req.method === 'OPTIONS') { res.writeHead(204, cors); res.end(); return; }
  if (req.headers.authorization !== 'Bearer test-token') { res.writeHead(401, cors); res.end('{}'); return; }
  if (req.url.startsWith('/v1/occupancy')) { res.writeHead(200, cors); res.end(JSON.stringify({ clubId: 'live1', clubName: 'Живой клуб', clubCap: 200, people: 150, zones: [{ id: 'free', count: 30, capacity: 33, dwellMin: 17 }, { id: 'cardio', count: 20, capacity: 50 }, { id: 'legs', count: 10, capacity: 20 }], entrance: { in10: 12, out10: 8 }, flows: [] })); return; }
  if (req.url.startsWith('/v1/equipment')) { res.writeHead(200, cors); res.end(JSON.stringify({ items: [{ id: 'rack1', type: 'rack', n: 1, name: 'Силовая рама', status: 'IN_USE', etaMin: 6, x: 10, y: 10 }, { id: 'tread1', type: 'tread', n: 1, name: 'Беговая дорожка', status: 'AVAILABLE', x: 20, y: 20 }] })); return; }
  res.writeHead(404, cors); res.end('{}');
});
await new Promise(r => mock.listen(0, '127.0.0.1', r)); const MOCK = 'http://127.0.0.1:' + mock.address().port;

const browser = await chromium.launch({ args: ['--no-sandbox'] });
let n = 0, failed = 0;
const step = async (name, fn) => { try { await fn(); n++; console.log('  ok  ' + name); } catch (e) { failed++; console.error('  FAIL ' + name + '\n     ' + String(e.message).split('\n').slice(0, 4).join('\n     ')); } };
const errs = [];
async function open(vp = { width: 390, height: 844 }, mobile = true) {
  const ctx = await browser.newContext({ viewport: vp, deviceScaleFactor: 1, isMobile: mobile, hasTouch: mobile });
  const page = await ctx.newPage();
  page.on('console', m => { if (m.type() === 'error') errs.push(m.text()); }); page.on('pageerror', e => errs.push('PAGEERROR: ' + e.message));
  await page.goto(BASE, { waitUntil: 'load' }); await page.waitForTimeout(1900); return { page, ctx };
}
const T = async (page, min = 19 * 60 + 5, dow = 2) => { await page.evaluate(([m, d]) => { const B = window.DDX; B.state.tOver = { dow: d, min: m, at: performance.now() }; B.initSim(); B.render(true); }, [min, dow]); await page.waitForTimeout(1300); };

const { page } = await open();
console.log('— старые функции');
await step('приложение загрузилось, мост и AI-слой на месте', async () => { assert.equal(await page.evaluate(() => typeof window.DDX + typeof window.DDXAI), 'objectobject'); assert.ok(await page.evaluate(() => !!window.DDXAI.ui)); assert.ok(await page.evaluate(() => document.querySelector('[data-splash]').classList.contains('is-off'))); });
await step('главный экран: загрузка и люди', async () => { await T(page); const t = await page.textContent('[data-load]'); assert.ok(/\d+/.test(t)); assert.ok(+(await page.textContent('[data-people]')) > 0); });
await step('вкладки: Зал → Шкафчик → Прогноз → Клуб', async () => { for (const s of ['map', 'lockers', 'forecast', 'home']) { await page.click(`.tab[data-go="${s}"]`); await page.waitForTimeout(500); assert.ok(await page.evaluate(n => document.querySelector(`[data-screen="${n}"]`).classList.contains('is-on'), s), s); } });
await step('карточка тренажёра открывается и «Позвать» работает', async () => { await page.evaluate(() => window.DDX.openEq('legpress1')); await page.waitForTimeout(500); assert.ok(await page.evaluate(() => window.DDX.sheet.classList.contains('is-on'))); const b = await page.$('[data-eqact="watch"]'); if (b) { await b.click(); await page.waitForTimeout(300); assert.ok(await page.evaluate(() => window.DDX.state.watch.size === 1)); } await page.evaluate(() => { window.DDX.state.watch.clear(); window.DDX.closeSheet(); }); });
await step('шкафчики: выбрать раздевалку, забронировать, отменить', async () => { await page.click('.tab[data-go="lockers"]'); await page.waitForTimeout(500); if (await page.$('[data-lkroom="f"]')) await page.click('[data-lkroom="f"]'); await page.waitForTimeout(400); const b = await page.$('[data-lkbook]'); assert.ok(b); await b.click(); await page.waitForTimeout(600); assert.ok(await page.evaluate(() => !!window.DDX.state.lk)); await page.evaluate(() => document.querySelector('[data-lkact="cancel"]') && document.querySelector('[data-lkact="cancel"]').click()); await page.waitForTimeout(300); assert.ok(await page.evaluate(() => !window.DDX.state.lk)); await page.click('.tab[data-go="home"]'); });
await step('маршрут: цель → старт тренировки → шаг → завершение', async () => { await page.evaluate(() => { window.DDX.state.goal = 'legs'; window.DDX.renderGoals(); window.DDX.buildPlan(true); window.DDX.go('plan'); }); await page.waitForTimeout(500); await page.click('[data-act="start"]'); await page.waitForTimeout(700); assert.ok(await page.evaluate(() => !!window.DDX.state.wo)); await page.click('[data-wo-done]'); await page.waitForTimeout(300); await page.click('[data-wo-x]'); await page.waitForTimeout(500); assert.ok(await page.evaluate(() => !window.DDX.state.wo)); await page.evaluate(() => window.DDX.go('home')); });
await step('DDX AI (чат): вопрос и ответ', async () => { await page.evaluate(() => window.DDX.go('home')); await page.waitForTimeout(300); await page.click('[data-act="ai"]'); await page.waitForTimeout(500); await page.fill('[data-chatin]', 'сколько людей сейчас'); await page.press('[data-chatin]', 'Enter'); await page.waitForTimeout(1600); assert.ok((await page.textContent('[data-log]')).includes('Сейчас')); await page.evaluate(() => window.DDX.closeSheet()); });
await step('тайм-машина и смена клуба', async () => { await page.evaluate(() => document.querySelector('[data-timepill]').click()); await page.waitForTimeout(400); assert.ok(await page.evaluate(() => window.DDX.sheet.classList.contains('is-on'))); await page.evaluate(() => { document.querySelector('[data-tpeak]').click(); window.DDX.closeSheet(); }); await page.waitForTimeout(400); await page.evaluate(() => { window.DDX.sheet.classList.remove('is-on'); }); });
await step('классический пульт управляющего открывается', async () => { await page.evaluate(() => window.DDX.go('admin')); await page.waitForTimeout(900); assert.ok(await page.evaluate(() => document.querySelectorAll('[data-kpis] .kpi').length === 4)); assert.ok(await page.evaluate(() => document.querySelectorAll('[data-alerts] .al').length > 0)); await page.evaluate(() => window.DDX.go('home')); });
await step('старые OFFLINE-станции недоступны и в старом маршруте', async () => { assert.equal(await page.evaluate(() => window.DDX.stOf('ellip2')), 'service'); });

console.log('— AI LIVE');
await T(page, 19 * 60);
await step('главная: карточка AI LIVE, переход на экран', async () => { await page.evaluate(() => window.DDX.go('home')); await page.waitForTimeout(600); assert.ok((await page.textContent('[data-ailive]')).includes('AI LIVE')); await page.click('[data-ailive] .aic'); await page.waitForTimeout(900); assert.equal(await page.evaluate(() => window.DDX.state.screen), 'live'); });
await step('AI LIVE: 10 зон на схеме, 4 строки статуса, DEMO-метка', async () => { assert.equal(await page.evaluate(() => document.querySelectorAll('[data-twsvg] .tz').length), 10); assert.equal(await page.evaluate(() => document.querySelectorAll('[data-zr]').length >= 4), true); assert.ok((await page.textContent('[data-screen="live"] .ai-badge')).includes('DEMO')); assert.ok(await page.evaluate(() => document.querySelectorAll('[data-twsvg] .eqd').length === 54)); });
await step('AI LIVE: вкладки Прогноз и Тренажёры', async () => { await page.click('[data-seg="aitab"] [data-v="forecast"]'); await page.waitForTimeout(500); assert.ok((await page.textContent('[data-aipane="forecast"]')).includes('+15')); await page.click('[data-seg="aitab"] [data-v="equip"]'); await page.waitForTimeout(500); assert.ok((await page.textContent('[data-aipane="equip"]')).match(/AVAILABLE|IN USE|QUEUE/)); await page.click('[data-seg="aitab"] [data-v="map"]'); });
await step('лист зоны: люди, индикатор, время на станции, прогноз +15', async () => { await page.evaluate(() => window.DDXAI.ui.openZone('free')); await page.waitForTimeout(500); const t = await page.textContent('[data-sheet-b]'); for (const k of ['PEOPLE NOW', 'CAPACITY INDICATOR', 'AVG DWELL TIME', 'PREDICTION +15 MIN']) assert.ok(t.includes(k), k); await page.evaluate(() => window.DDX.closeSheet()); });
await step('слои карты переключаются', async () => { await page.click('[data-twl] [data-l="ppl"]'); await page.waitForTimeout(200); assert.ok(await page.evaluate(() => document.querySelector('[data-twsvg]').classList.contains('no-ppl'))); await page.click('[data-twl] [data-l="ppl"]'); });

console.log('— Command Center и приватность');
await step('роль «Посетитель» → доступ закрыт, вход как управляющий', async () => { await page.evaluate(() => { window.DDXAI.privacy.setRole('member'); window.DDX.go('command'); }); await page.waitForTimeout(700); assert.ok(await page.isVisible('[data-cc-login]')); await page.click('[data-cc-login]'); await page.waitForTimeout(600); assert.ok(await page.isVisible('[data-cs="kpi"]')); });
await step('Command Center: 6 показателей и все блоки', async () => { assert.equal(await page.evaluate(() => document.querySelectorAll('[data-cs="kpi"] .cc-k').length), 6); const t = await page.textContent('[data-command]'); for (const k of ['PEOPLE INSIDE', 'CLUB LOAD', 'PEAK PREDICTION', 'CRITICAL ZONES', 'EQUIPMENT ALERTS', 'AI OPERATIONAL EVENTS', 'Live heatmap', 'Predicted congestion', 'Equipment status', 'Traffic', 'Vision events', 'Operational alerts', 'Return engine', 'Ask DDX AI', 'Daily AI report', 'PEAK OCCUPANCY', 'MOST LOADED ZONE', 'AVERAGE CONGESTION']) assert.ok(t.includes(k) || t.toUpperCase().includes(k.toUpperCase()), k); });
await step('AI-вопрос: ответ строится по данным и показывает источники', async () => { await page.fill('[data-cc-in]', 'Что сейчас происходит в клубе?'); await page.press('[data-cc-in]', 'Enter'); await page.waitForTimeout(500); const t = await page.textContent('[data-cc-log]'); assert.ok(/Загрузка клуба — \d+%/.test(t), t); assert.ok(t.includes('Occupancy Engine')); });
await step('камера зоны: доступ записывается в журнал; зона без камер — отказ', async () => { const before = await page.evaluate(() => window.DDXAI.privacy.audit.length); await page.evaluate(() => window.DDXAI.ui.openCamera('free')); await page.waitForTimeout(500); assert.ok(await page.isVisible('[data-zcam]')); assert.equal(await page.evaluate(() => window.DDXAI.privacy.audit[0].action), 'camera.open'); await page.evaluate(() => window.DDXAI.ui.openCamera('locker')); await page.waitForTimeout(300); assert.equal(await page.evaluate(() => window.DDXAI.privacy.audit[0].action), 'camera.denied'); await page.evaluate(() => window.DDX.closeSheet()); });
await step('«Данные и согласия»: тумблеры, сроки, журнал, удаление', async () => { await page.evaluate(() => window.DDXAI.ui.openPrivacyAI()); await page.waitForTimeout(400); await page.click('[data-cons="inbody"]'); await page.waitForTimeout(200); assert.equal(await page.evaluate(() => window.DDXAI.privacy.consent.sources.inbody), false); await page.click('[data-ret="analyticsDays:30"]'); assert.equal(await page.evaluate(() => window.DDXAI.privacy.retention.analyticsDays), 30); assert.ok((await page.textContent('[data-sheet-b]')).includes('не хранится')); await page.click('[data-deldata]'); await page.waitForTimeout(300); assert.equal(await page.evaluate(() => window.DDXAI.privacy.consent.sources.inbody), true); await page.evaluate(() => window.DDX.closeSheet()); });

console.log('— Vision Coach');
await step('без согласия сессию не запустить', async () => { await page.evaluate(() => window.DDX.go('coach')); await page.waitForTimeout(500); await page.click('[data-costart]'); await page.waitForTimeout(300); assert.ok(await page.isVisible('[data-coconsent]')); assert.equal(await page.evaluate(() => window.DDXAI.ui.coach.phase), 'intro'); });
await step('сессия: распознавание, повторы, метрики, завершение', async () => { await page.click('[data-coex="curl"]'); await page.check('[data-coconsent]'); await page.click('[data-costart]'); await page.evaluate(() => { window.DDXAI.ui.coach.speed = 5; }); await page.waitForTimeout(9000); const v = await page.evaluate(() => { const c = window.DDXAI.ui.coach.sess.view(); return { ex: c.exercise, reps: c.reps }; }); assert.equal(v.ex, 'curl'); assert.ok(v.reps >= 4, 'повторов ' + v.reps); assert.ok((await page.textContent('[data-co="rangeS"]')).includes('°')); await page.click('[data-coend]'); await page.waitForTimeout(500); const t = await page.textContent('[data-coach]'); assert.ok(t.includes('SET COMPLETE') && t.includes('0 Б')); assert.equal(await page.evaluate(() => window.DDXAI.privacy.audit.some(a => a.action === 'session.close')), true); });

console.log('— Body Twin и Return Engine');
await step('Опытный: +14% / 82% / +11% / 78% / ON TRACK', async () => { await page.evaluate(() => { window.DDXAI.ui.bt.profile = 'pro'; window.DDXAI.ui.bt.exKey = null; window.DDX.go('twin'); }); await page.waitForTimeout(900); const t = await page.textContent('[data-twin]'); for (const k of ['+14%', '82%', '+11%', '78%', 'ON TRACK']) assert.ok(t.includes(k), k); });
await step('Новый: INSUFFICIENT DATA вместо выдуманных чисел', async () => { await page.click('[data-btp="new"]'); await page.waitForTimeout(700); const t = await page.textContent('[data-twin]'); assert.ok((t.match(/INSUFFICIENT DATA/g) || []).length >= 4, t.slice(0, 200)); assert.ok(!t.includes('+14%')); });
await step('Возвращение: WELCOME BACK и мягкая тренировка', async () => { await page.click('[data-btp="back"]'); await page.waitForTimeout(700); assert.ok((await page.textContent('[data-twin]')).includes('WELCOME BACK')); await page.click('[data-btwb]'); await page.waitForTimeout(900); assert.ok(await page.evaluate(() => !!window.DDX.state.wo && !!window.DDX.state.plan.welcome)); assert.equal(await page.evaluate(() => window.DDX.state.plan.order.length), 5); assert.ok((await page.textContent('[data-wo]')).includes('WELCOME BACK')); await page.click('[data-wo-x]'); await page.waitForTimeout(400); });
await step('отзыв согласия на InBody убирает композицию тела', async () => { await page.evaluate(() => { window.DDXAI.ui.bt.profile = 'pro'; window.DDXAI.privacy.consent.sources.inbody = false; window.DDXAI.ui.onConsent(); window.DDX.go('twin'); }); await page.waitForTimeout(700); const t = await page.textContent('[data-twin]'); assert.ok(t.includes('нет согласия на источник')); await page.evaluate(() => { window.DDXAI.privacy.consent.sources.inbody = true; }); });

console.log('— динамический маршрут');
await step('занятое упражнение → ROUTE UPDATED с заменой и расстоянием; «вернуть как было»', async () => {
  await page.evaluate(() => { const A = window.DDXAI, B = window.DDX; A.scenario.start(); A.orch.attachScenario(A.scenario); A.ui.refresh(); const ex = [['Жим от груди', 'chest', 3], ['Жим вверх', 'shoulder', 3], ['Разведение гантелей', 'db', 3], ['Эллипс', 'ellip', 1]]; B.state.plan = { goal: 'chest', dur: 45, order: ex.map(e => ({ ex: e, id: null, wait: 0, at: 0 })), total: 40, wait: 0, naive: 4, changed: false }; B.startWorkout(); });
  await page.waitForTimeout(1800); const t = await page.textContent('[data-wo]'); assert.ok(t.includes('ROUTE UPDATED') && t.includes('Кроссовер') && /\d+ м/.test(t), t.slice(0, 300));
  assert.equal(await page.evaluate(() => window.DDX.state.plan.order.length), 4);
  await page.click('[data-routeundo]'); await page.waitForTimeout(500); assert.equal(await page.evaluate(() => window.DDX.state.plan.order[0].ex[0]), 'Жим от груди'); await page.click('[data-wo-x]'); await page.waitForTimeout(300); await page.evaluate(() => { window.DDXAI.scenario.stop(); window.DDXAI.ui.refresh(); window.DDX.go('home'); });
});

console.log('— LIVE-адаптер (против мок-сервера)');
await step('LIVE без адреса отклоняется, остаёмся в DEMO', async () => { await page.evaluate(() => window.DDXAI.ui.openMode()); await page.waitForTimeout(400); await page.fill('[data-live-url]', 'не-адрес'); await page.click('[data-livego]'); await page.waitForTimeout(300); assert.equal(await page.evaluate(() => window.DDXAI.orch.mode), 'DEMO'); });
await step('LIVE с неверным токеном — ошибка, DEMO сохраняется', async () => { await page.fill('[data-live-url]', MOCK); await page.fill('[data-live-token]', 'wrong'); await page.click('[data-livego]'); await page.waitForTimeout(1500); assert.equal(await page.evaluate(() => window.DDXAI.orch.mode), 'DEMO'); assert.ok((await page.textContent('[data-live-msg]')).includes('Не удалось')); });
await step('LIVE с верным токеном: данные из сервиса, без подмены демо', async () => { await page.fill('[data-live-token]', 'test-token'); await page.click('[data-livego]'); await page.waitForTimeout(1800); assert.equal(await page.evaluate(() => window.DDXAI.orch.mode), 'LIVE'); const s = await page.evaluate(() => { const x = window.DDXAI.ui.snap(); return { people: x.people, zones: x.zones.length, items: x.eq.items.length, name: x.clubName }; }); assert.equal(s.people, 150); assert.equal(s.name, 'Живой клуб'); assert.equal(s.items, 2); await page.evaluate(() => window.DDX.closeSheet()); await page.evaluate(() => window.DDX.go('live')); await page.waitForTimeout(800); assert.ok((await page.textContent('[data-screen="live"] .ai-badge')).includes('LIVE')); });
await step('возврат в DEMO', async () => { await page.evaluate(() => { window.DDXAI.ui.openMode(); }); await page.waitForTimeout(300); await page.click('[data-modego]'); await page.waitForTimeout(500); assert.equal(await page.evaluate(() => window.DDXAI.orch.mode), 'DEMO'); await page.evaluate(() => window.DDX.closeSheet()); });

console.log('— демо-сценарий');
await step('сценарий проходит все шаги и возвращает приложение в исходное состояние', async () => { const roleBefore = await page.evaluate(() => window.DDXAI.privacy.role); await page.evaluate(() => window.DDX.go('home')); await page.evaluate(() => window.DDX.acts.demo()); await page.waitForTimeout(500); assert.ok(await page.evaluate(() => window.DDXAI.ui.demo.state.on)); const count = await page.evaluate(() => window.DDXAI.ui.demo.steps.length); for (let i = 1; i < count; i++) { await page.evaluate(i => window.DDXAI.ui.demo.go(i), i); await page.waitForTimeout(i === 7 ? 4200 : 1100); } assert.ok((await page.textContent('[data-demo-full]')).includes('SEES')); await page.click('[data-demo-full] [data-dx]'); await page.waitForTimeout(700); assert.ok(await page.evaluate(r => !window.DDXAI.ui.demo.state.on && !window.DDXAI.scenario.active && window.DDXAI.privacy.role === r && window.DDX.state.screen === 'home', roleBefore)); });

// настольная раскладка
const d = await open({ width: 1366, height: 820 }, false);
await step('компьютер: боковые панели и телефон на месте, AI-кнопки в левой панели', async () => { assert.ok(await d.page.isVisible('.pitch')); assert.ok(await d.page.isVisible('.how')); assert.ok(await d.page.isVisible('.pitch [data-act="demo"]')); await d.page.click('.pitch [data-act="live"]'); await d.page.waitForTimeout(800); assert.equal(await d.page.evaluate(() => window.DDX.state.screen), 'live'); await d.page.screenshot({ path: process.env.SHOT_DESKTOP || '/tmp/ddx-desktop.png' }); });
await step('нет ошибок консоли за весь прогон (кроме намеренного отказа 401 в проверке LIVE)', async () => { const real = errs.filter(e => !/status of 401/.test(e)); assert.equal(real.length, 0, real.join('\n')); });
await browser.close(); srv.close(); mock.close();
console.log(`\nE2E: ${n} пройдено, ${failed} провалено`); process.exit(failed ? 1 : 0);
